// Reads pre-matched data from data.json (generated by scripts/scrape.js via GitHub Actions)

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function pct(p) {
  return p != null ? (p * 100).toFixed(1) + '¢' : 'N/A';
}

function diffClass(d) {
  if (d >= 10) return 'large';
  if (d >= 5)  return 'notable';
  return '';
}

function renderPair(pair) {
  const { polymarket: pm, kalshi: km, score, diff, arb, arbProfit, buyYesOn, buyNoOn } = pair;
  const pmCheaper = pm.yesPrice <= km.yesPrice;

  const card = document.createElement('div');
  card.className = 'card' + (arb ? ' arb' : '');
  card.dataset.arb = arb ? '1' : '0';

  card.innerHTML = `
    <div class="card-title">${esc(pm.title)}</div>
    ${arb ? `
      <div class="arb-badge">
        ⚡ Arb: buy YES on ${esc(buyYesOn)}, NO on ${esc(buyNoOn)} · +${arbProfit}¢ per $1
      </div>` : ''}
    <div class="markets">
      <div class="market">
        <div class="platform-name">Polymarket</div>
        <div class="prices">
          <span class="price${pmCheaper ? ' cheaper' : ''}">YES ${pct(pm.yesPrice)}</span>
          <span class="price">NO ${pct(pm.noPrice)}</span>
        </div>
        <a href="${esc(pm.url)}" target="_blank" rel="noopener" class="market-link">View on Polymarket →</a>
      </div>

      <div class="divider">
        <span class="diff ${diffClass(diff)}">Δ ${diff}¢</span>
      </div>

      <div class="market">
        <div class="platform-name">Kalshi</div>
        <div class="prices">
          <span class="price${!pmCheaper ? ' cheaper' : ''}">YES ${pct(km.yesPrice)}</span>
          <span class="price">NO ${pct(km.noPrice)}</span>
        </div>
        <div class="kalshi-title">${esc(km.title)}</div>
        <a href="${esc(km.url)}" target="_blank" rel="noopener" class="market-link">View on Kalshi →</a>
      </div>
    </div>
    <div class="match-score">Match confidence: ${score}%</div>
  `;

  return card;
}

async function main() {
  const grid   = document.getElementById('grid');
  const count  = document.getElementById('count');
  const updated = document.getElementById('updated');

  try {
    const res  = await fetch('data.json?t=' + Date.now());
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();

    const arbCount = data.matches.filter(m => m.arb).length;
    count.textContent   = `${data.matchCount} matched pairs · ${arbCount} arb opportunities · ${data.polymarketCount} Polymarket + ${data.kalshiCount} Kalshi markets`;
    updated.textContent = 'Last updated: ' + new Date(data.lastUpdated).toLocaleString();

    grid.innerHTML = '';
    if (!data.matches.length) {
      grid.innerHTML = '<p class="empty">No matching markets found.</p>';
      return;
    }

    for (const pair of data.matches) grid.appendChild(renderPair(pair));

    document.getElementById('arbOnly').addEventListener('change', e => {
      document.querySelectorAll('.card').forEach(el => {
        el.style.display = e.target.checked && el.dataset.arb !== '1' ? 'none' : '';
      });
    });

  } catch (e) {
    grid.innerHTML = `<p class="empty">Could not load data.json — run the GitHub Action first, or run <code>node scripts/scrape.js</code> locally.<br><br>${esc(e.message)}</p>`;
    count.textContent = 'Data unavailable';
    console.error(e);
  }
}

main();
